name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Flutter Engine
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.x'
        channel: 'stable'

    - name: Create Flutter App
      run: |
        flutter create . --overwrite --project-name ultrakartik
        
    - name: Build Android APK
      run: flutter build apk --release --no-tree-shake-icons

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Ultrakartik-App-APK
        path: build/app/outputs/flutter-apk/app-release.apk
